name: cd

on:
  push:
    branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
          - name: Check out code
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: "1.25.1"

          - name: Build for production
            run: |
              chmod +x ./scripts/buildprod.sh
              ./scripts/buildprod.sh

        #   - name: Log in to Docker Hub
        #     uses: docker/login-action@v2
        #     with:
        #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
        #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        #   - name: Build and push Docker image
        #     uses: docker/build-push-action@v4
        #     with:
        #       context: .
        #       push: true
        #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/notely:latest
